;; -*- lexical-binding: t -*-

(defun read-grid (file)
  (with-temp-buffer
    (insert-file-contents file)
    (let* ((height (line-number-at-pos (1- (point-max))))
	   (grid (make-vector height nil)))
      (dotimes (i height)
	(let ((row (buffer-substring (point) (line-end-position))))
	  (aset grid i row)
	  (forward-line)))
      grid)))

(defun insert-grid (grid)
  (seq-do (lambda (row)
	    (insert row)
	    (insert ?\n))
	  grid))

(defun grid-height (grid)
  (length grid))

(defun grid-width (grid)
  (length (aref grid 0)))

(defun gset (grid pos value)
  "Ignores out-of-bounds references"
  (pcase-let* ((`(,i . ,j) pos))
    (when (and (>= i 0) (< i (length grid)))
      (let ((row (aref grid i)))
	(when (and (>= j 0) (< j (length row)))
	  (aset row j value))))))

(defun gref (grid pos)
  "Returns nil for out-of-bounds references"
  (pcase-let* ((`(,i . ,j) pos))
    (when (and (>= i 0) (< i (length grid)))
      (let ((row (aref grid i)))
	(when (and (>= j 0) (< j (length row)))
	  (aref row j))))))

(defun make-grid (height width)
  (let ((grid (make-vector height nil)))
    (dotimes (i height)
      (aset grid i (make-string width ?.)))
    grid))

(defun grid-like (grid)
  (make-grid (grid-height grid) (grid-width grid)))

(defun map-grid (function grid)
  (dotimes (i (grid-height grid))
    (dotimes (j (grid-width grid))
      (let ((pos (cons i j)))
	(funcall function pos (gref grid pos))))))

(defun find-animal (grid)
  (catch :found
    (dotimes (i (grid-height grid))
      (dotimes (j (grid-width grid))
	(let ((pos (cons i j)))
	  (when (eq (gref grid pos) ?S)
	    (throw :found pos)))))))

(defun around (pos)
  (pcase-let ((`(,i . ,j) pos))
    (list (cons i (1+ j))
	  (cons (1+ i) j)
	  (cons (1- i) j)
	  (cons i (1- j)))))

(defun pipe-ends (pos grid)
  (let ((c (gref grid pos)))
    (pcase-let ((`(,i . ,j) pos))
      (pcase c
	(?| `((,(1- i) . ,j) . (,(1+ i) . ,j)))
	(?- `((,i . ,(1- j)) . (,i . ,(1+ j))))
	(?L `((,(1- i) . ,j) . (,i . ,(1+ j))))
	(?J `((,(1- i) . ,j) . (,i . ,(1- j))))
	(?7 `((,(1+ i) . ,j) . (,i . ,(1- j))))
	(?F `((,(1+ i) . ,j) . (,i . ,(1+ j))))))))

(defun connectedp (pos to grid)
  (pcase-let ((`(,a . ,b) (pipe-ends pos grid)))
    (or (equal to a) (equal to b))))

(defun other-end (pos other grid)
  (pcase-let ((`(,a . ,b) (pipe-ends pos grid)))
    (if (equal other a) b a)))

(defun puzzle-10a ()
  (let* ((grid (read-grid "data/input-10.txt"))
	 (start (find-animal grid))
	 (prev-a start)
	 (prev-b start)
	 (a nil)
	 (b nil)
	 (count 1)
	 (finish nil))
    (dolist (pos (around start))
      (when (connectedp pos start grid)
	(if (null a)
	    (setq a pos)
	  (setq b pos))))
    (while (null finish)
      (setq count (1+ count))
      (let ((next-a (other-end a prev-a grid))
	    (next-b (other-end b prev-b grid)))
	(if (equal next-a next-b)
	    (setq finish t)
	  (setq prev-a a)
	  (setq a next-a)
	  (setq prev-b b)
	  (setq b next-b))))
    count))

(defun paint-bucket (grid pos value)
  (let ((area (list pos))
	(old (gref grid pos)))
    (gset grid pos value)
    (while area
      (let ((fresh nil))
	(dolist (pos area)
	  (dolist (pos (around pos))
	    (when (eq (gref grid pos) old)
	      (gset grid pos value)
	      (push pos fresh))))
	(setq area fresh)))))

(defun northwestp (a b)
  (pcase-let ((`(,ai . ,aj) a)
	      (`(,bi . ,bj) b))
    (or (< ai bi) (and (= ai bi) (< aj bj)))))

(defun reorient (list elem)
  (let ((head list)
	(last (last list))
	(prev nil))
    (catch :done
      (while head
	(if (equal (car head) elem)
	    (progn
	      (when prev
		(setcdr last list)
		(setcdr prev nil))
	      (throw :done head))
	  (setq prev head)
	  (setq head (cdr head)))))))

(defun clockwise-path (grid start)
  (let ((prev start)
	(pos nil)
	(corner nil)
	(path (list start)))
    (dolist (a (around start))
      (when (and (null pos) (connectedp a start grid))
	(setq pos a)))
    (while (not (equal pos start))
      (push pos path)
      (let ((next (other-end pos prev grid)))
	(setq prev pos)
	(setq pos next)
	(when (or (null corner)
		  (northwestp pos corner))
	  (setq corner pos))))
    (reorient path corner)))

(defun inside (a b)
  (pcase-let ((`(,ai . ,aj) a))
    (cond ((equal b `(,ai . ,(1+ aj))) 'MAY)
	  ((equal b `(,ai . ,(1- aj))) 'YOU)
	  ((equal b `(,(1+ ai) . ,aj)) 'BEE)
	  ((equal b `(,(1- ai) . ,aj)) 'BUM)
	  (t (error "Unexpected move: %s ⇒ %s" a b)))))

(defun puzzle-10b ()
  (let* ((grid (read-grid "data/example-10a.txt"))
	 (trace (grid-like grid))
	 (start (find-animal grid))
	 (path (clockwise-path grid start)))
    (let ((prev nil))
      (dolist (pos path)
	(gset trace pos ?X)
	(if (null prev)
	    (setq prev pos)
	  (let ((seed (inside prev pos)))
	    (gset trace pos ?I))
	  (setq prev pos))))
    (insert-grid trace)))
