;; -*- lexical-binding: t -*-

(defun read-grid (file)
  (with-temp-buffer
    (insert-file-contents file)
    (let* ((height (line-number-at-pos (1- (point-max))))
	   (grid (make-vector height nil)))
      (dotimes (i height)
	(let ((row (buffer-substring (point) (line-end-position))))
	  (aset grid i row)
	  (forward-line)))
      grid)))

(defun insert-grid (grid)
  (seq-do (lambda (row)
	    (insert row)
	    (insert ?\n))
	  grid))

(defun grid-height (grid)
  (length grid))

(defun grid-width (grid)
  (length (aref grid 0)))

(defun gset (grid pos value)
  "Ignores out-of-bounds references"
  (pcase-let* ((`(,i . ,j) pos))
    (when (and (>= i 0) (< i (length grid)))
      (let ((row (aref grid i)))
	(when (and (>= j 0) (< j (length row)))
	  (aset row j value))))))

(defun gref (grid pos)
  "Returns nil for out-of-bounds references"
  (pcase-let* ((`(,i . ,j) pos))
    (when (and (>= i 0) (< i (length grid)))
      (let ((row (aref grid i)))
	(when (and (>= j 0) (< j (length row)))
	  (aref row j))))))

(defun make-grid (height width)
  (let ((grid (make-vector height nil)))
    (dotimes (i height)
      (aset grid i (make-string width ?.)))
    grid))

(defun grid-like (grid)
  (make-grid (grid-height grid) (grid-width grid)))

(defun find-animal (grid)
  (catch :found
    (dotimes (i (grid-height grid))
      (dotimes (j (grid-width grid))
	(let ((pos (cons i j)))
	  (when (eq (gref grid pos) ?S)
	    (throw :found pos)))))))

(defun around (pos)
  (pcase-let ((`(,i . ,j) pos))
    (list (cons i (1+ j))
	  (cons (1+ i) j)
	  (cons (1- i) j)
	  (cons i (1- j)))))

(defun pipe-ends (pos grid)
  (let ((c (gref grid pos)))
    (pcase-let ((`(,i . ,j) pos))
      (pcase c
	(?| `((,(1- i) . ,j) . (,(1+ i) . ,j)))
	(?- `((,i . ,(1- j)) . (,i . ,(1+ j))))
	(?L `((,(1- i) . ,j) . (,i . ,(1+ j))))
	(?J `((,(1- i) . ,j) . (,i . ,(1- j))))
	(?7 `((,(1+ i) . ,j) . (,i . ,(1- j))))
	(?F `((,(1+ i) . ,j) . (,i . ,(1+ j))))))))

(defun connectedp (pos to grid)
  (pcase-let ((`(,a . ,b) (pipe-ends pos grid)))
    (or (equal to a) (equal to b))))

(defun other-end (pos other grid)
  (pcase-let ((`(,a . ,b) (pipe-ends pos grid)))
    (if (equal other a) b a)))

(defun puzzle-10a ()
  (let* ((grid (read-grid "data/input-10.txt"))
	 (start (find-animal grid))
	 (prev-a start)
	 (prev-b start)
	 (a nil)
	 (b nil)
	 (count 1)
	 (finish nil))
    (dolist (pos (around start))
      (when (connectedp pos start grid)
	(if (null a)
	    (setq a pos)
	  (setq b pos))))
    (while (null finish)
      (setq count (1+ count))
      (let ((next-a (other-end a prev-a grid))
	    (next-b (other-end b prev-b grid)))
	(if (equal next-a next-b)
	    (setq finish t)
	  (setq prev-a a)
	  (setq a next-a)
	  (setq prev-b b)
	  (setq b next-b))))
    count))

(defun map-perimeter (function grid)
  (let ((height (grid-height grid))
	(width (grid-width grid)))
    (let ((i 0))
      (dotimes (j width)
	(funcall function (cons i j))))
    (let ((i (1- height)))
      (dotimes (j width)
	(funcall function (cons i j))))
    (let ((j 0))
      (dotimes (i (- height 2))
	(funcall function (cons (1+ i) j))))
    (let ((j (1- width)))
      (dotimes (i (- height 2))
	(funcall function (cons (1+ i) j))))))

(defun paint-bucket (grid pos value)
  (let ((area (list pos))
	(old (gref grid pos)))
    (gset grid pos value)
    (while area
      (let ((fresh nil))
	(dolist (pos (around pos))
	  (when (eq (gref grid pos) old)
	    (gset grid pos value)
	    (push pos fresh)))
	(setq area fresh)))))

(defun puzzle-10b ()
  (let* ((grid (read-grid "data/example-10.txt"))
	 (trace (grid-like grid))
	 (start (find-animal grid))
	 (prev start)
	 (pos nil))
    (dolist (a (around start))
      (when (and (null pos) (connectedp a start grid))
	(setq pos a)))
    (while (not (equal pos start))
      (let ((next (other-end pos prev grid)))
	(gset trace pos ?X)
	(setq prev pos)
	(setq pos next)))
    (map-perimeter
     (lambda (pos)
       (when (eq (gref trace pos) ?.)
	 (paint-bucket trace pos ?O)))
     trace)
    ;; run perimeter
    ;; mark any ?. transitively as ?O for outside
    ;; count remaining ?. for inside
    (insert-grid trace)))
