;; -*- lexical-binding: t -*-

(defun read-line ()
  (prog1
      (buffer-substring (point) (line-end-position))
    (forward-line)))

(defun read-list (string)
  (read (concat "(" string ")")))

(defun read-histories (file)
  (with-temp-buffer
    (insert-file-contents file)
    (let ((hists nil))
      (while (not (eobp))
	(let* ((line (read-line))
	       (hist (read-list line)))
	  (push hist hists)))
      (nreverse hists))))

(defun deltas (list)
  (let ((deltas nil)
	(a (pop list)))
    (while-let ((b (pop list)))
      (push (- b a) deltas)
      (setq a b))
    (nreverse deltas)))

(defun sequences (list)
  (let ((seqs (list list)))
    (while (not (seq-every-p #'zerop list))
      (setq list (deltas list))
      (push list seqs))
    (nreverse seqs)))

(defun next-right (seqs)
  (let* ((seqs (reverse seqs))
	 (lasts (mapcar #'car (mapcar #'reverse seqs))))
    (seq-reduce #'+ lasts 0)))

(defun puzzle-9a ()
  (let ((hists (read-histories "data/input-9.txt"))
	(sum 0))
    (dolist (hist hists)
      (let* ((seqs (sequences hist))
	     (next (next-right seqs)))
	(incf sum next)))
    sum))

(defun next-left (seqs)
  (let* ((seqs (cdr (reverse seqs)))
	 (firsts (mapcar #'car seqs))
	 (n 0))
    (dolist (first firsts)
      (setq n (- first n)))
    n))

(defun puzzle-9b ()
  (let ((hists (read-histories "data/input-9.txt"))
	(sum 0))
    (dolist (hist hists)
      (let* ((seqs (sequences hist))
	     (next (next-left seqs)))
	(incf sum next)))
    sum))
