;; -*- lexical-binding: t -*-

(defun read-records (file)
  (with-temp-buffer
    (insert-file-contents file)
    (let ((records nil))
      (while (not (eobp))
	(let ((start (point))
	      (springs nil)
	      (sizes nil))
	  (re-search-forward " ")
	  (setq springs (buffer-substring start (1- (point))))
	  (let* ((text (buffer-substring (point) (line-end-position)))
		 (split (split-string text ",")))
	    (setq sizes (mapcar #'read split)))
	  (push (cons springs sizes) records))
	(forward-line))
      (nreverse records))))

(defmacro defmemo (name arglist &rest body)
  (declare (indent 2))
  (let ((table (gensym))
	(result (gensym))
	(key (gensym)))
    `(let ((,table (make-hash-table :test 'equal)))
       (defun ,name ,arglist
	 (let ((,key (list ,@arglist)))
	   (if-let* ((,result (gethash ,key ,table)))
	       ,result
	     (let ((,result (progn ,@body)))
	       (puthash ,key ,result ,table))))))))

(defmemo ways (springs sizes)
  (let ((len (length springs)))
    (cond ((zerop len) (if sizes 0 1))
	  ((null sizes) (if (seq-contains-p springs ?#) 0 1))
	  (t (pcase (aref springs 0)
	       (?. (ways (substring springs 1) sizes))
	       (?# (let ((size (car sizes)))
		     (cond ((< len size) 0)
			   ((and (> len size)
				 (eq (aref springs size) ?#))
			    0)
			   ((let ((run (substring springs 0 size)))
			      (seq-contains-p run ?.))
			    0)
			   ((> len size)
			    (ways (substring springs (1+ size)) (cdr sizes)))
			   (t (ways "" (cdr sizes))))))
	       (?? (let ((rest (substring springs 1)))
		     (+ (ways (concat "#" rest) sizes)
			(ways (concat "." rest) sizes)))))))))

(defun puzzle-12a ()
  ;; example-12.txt: 21
  ;; input-12.txt: 7007
  (let* ((file "data/input-12.txt")
	 (records (read-records file))
	 (count 0))
    (dolist (row records)
      (incf count (ways (car row) (cdr row))))
    count))

(defun puzzle-12b ()
  ;; example-12.txt: 525152
  ;; input-12.txt: 3476169006222
  (let* ((file "data/input-12.txt")
	 (records (read-records file))
	 (count 0))
    (dolist (row records)
      (let* ((springs (car row))
	     (sizes (cdr row))
	     (sprungs (copy-sequence springs))
	     (suzes (copy-sequence sizes)))
	(dotimes (_ 4)
	  (setq sprungs (concat sprungs "?" (copy-sequence springs)))
	  (setq suzes (append suzes (copy-sequence sizes))))
	(incf count (ways sprungs suzes))))
    count))
