;; -*- lexical-binding: t -*-

(defun read-grid (file)
  (with-temp-buffer
    (insert-file-contents file)
    (let* ((height (line-number-at-pos (1- (point-max))))
	   (grid (make-vector height nil)))
      (dotimes (i height)
	(let ((row (buffer-substring (point) (line-end-position))))
	  (aset grid i row)
	  (forward-line)))
      grid)))

(defun grid-height (grid)
  (length grid))

(defun grid-width (grid)
  (length (aref grid 0)))

(defun gref (grid pos)
  (pcase-let ((`(,i . ,j) pos))
    (when (and (>= i 0) (< i (length grid)))
      (let ((row (aref grid i)))
	(when (and (>= j 0) (< j (length row)))
	  (aref row j))))))

(defun prospects (pos)
  (pcase-let ((`(,i . ,j) pos))
    `(((?M (,(- i 1) . ,(- j 1)))
       (?A (,(- i 2) . ,(- j 2)))
       (?S (,(- i 3) . ,(- j 3))))
      ((?M (,(- i 1) . ,j))
       (?A (,(- i 2) . ,j))
       (?S (,(- i 3) . ,j)))
      ((?M (,i . ,(- j 1)))
       (?A (,i . ,(- j 2)))
       (?S (,i . ,(- j 3))))
      ((?M (,(+ i 1) . ,(- j 1)))
       (?A (,(+ i 2) . ,(- j 2)))
       (?S (,(+ i 3) . ,(- j 3))))
      ((?M (,(- i 1) . ,(+ j 1)))
       (?A (,(- i 2) . ,(+ j 2)))
       (?S (,(- i 3) . ,(+ j 3))))
      ((?M (,(+ i 1) . ,(+ j 1)))
       (?A (,(+ i 2) . ,(+ j 2)))
       (?S (,(+ i 3) . ,(+ j 3))))
      ((?M (,(+ i 1) . ,j))
       (?A (,(+ i 2) . ,j))
       (?S (,(+ i 3) . ,j)))
      ((?M (,i . ,(+ j 1)))
       (?A (,i . ,(+ j 2)))
       (?S (,i . ,(+ j 3)))))))

(defun check-prospect (grid prospect)
  (seq-every-p
   (lambda (p)
     (pcase-let ((`(,c ,pos) p))
       (eq c (gref grid pos))))
   prospect))

(defun puzzle-4a ()
  ;; example-4.txt: 18
  ;; input-4.txt: 2543
  (let ((grid (read-grid "data/input-4.txt"))
	(count 0))
    (dotimes (i (grid-height grid))
      (dotimes (j (grid-width grid))
	(let ((pos (cons i j)))
	  (when (eq (gref grid pos) ?X)
	    (dolist (prospect (prospects pos))
	      (when (check-prospect grid prospect)
		(incf count)))))))
    count))

(defun prospects-2 (pos)
  (pcase-let ((`(,i . ,j) pos))
    `(((?M (,(- i 1) . ,(- j 1)))
       (?M (,(+ i 1) . ,(- j 1)))
       (?S (,(- i 1) . ,(+ j 1)))
       (?S (,(+ i 1) . ,(+ j 1))))
      ((?S (,(- i 1) . ,(- j 1)))
       (?M (,(+ i 1) . ,(- j 1)))
       (?S (,(- i 1) . ,(+ j 1)))
       (?M (,(+ i 1) . ,(+ j 1))))
      ((?M (,(- i 1) . ,(- j 1)))
       (?S (,(+ i 1) . ,(- j 1)))
       (?M (,(- i 1) . ,(+ j 1)))
       (?S (,(+ i 1) . ,(+ j 1))))
      ((?S (,(- i 1) . ,(- j 1)))
       (?S (,(+ i 1) . ,(- j 1)))
       (?M (,(- i 1) . ,(+ j 1)))
       (?M (,(+ i 1) . ,(+ j 1)))))))

(defun puzzle-4b ()
  ;; example-4.txt: 9
  ;; input-4.txt: 1930
  (let ((grid (read-grid "data/input-4.txt"))
	(count 0))
    (dotimes (i (grid-height grid))
      (dotimes (j (grid-width grid))
	(let ((pos (cons i j)))
	  (when (eq (gref grid pos) ?A)
	    (dolist (prospect (prospects-2 pos))
	      (when (check-prospect grid prospect)
		(incf count)))))))
    count))
