;; -*- lexical-binding: t -*-

(defun read-grid (file)
  (with-temp-buffer
    (insert-file-contents file)
    (let* ((height (line-number-at-pos (1- (point-max))))
	   (grid (make-vector height nil)))
      (dotimes (i height)
	(let ((row (buffer-substring (point) (line-end-position))))
	  (aset grid i row)
	  (forward-line)))
      grid)))

(defun insert-grid (grid)
  (seq-do (lambda (row)
	    (insert row)
	    (insert ?\n))
	  grid))

(defun grid-height (grid)
  (length grid))

(defun grid-width (grid)
  (length (aref grid 0)))

(defun gset (grid pos value)
  (pcase-let ((`(,i . ,j) pos))
    (when (and (>= i 0) (< i (length grid)))
      (let ((row (aref grid i)))
	(when (and (>= j 0) (< j (length row)))
	  (aset row j value))))))

(defun gref (grid pos)
  (pcase-let ((`(,i . ,j) pos))
    (when (and (>= i 0) (< i (length grid)))
      (let ((row (aref grid i)))
	(when (and (>= j 0) (< j (length row)))
	  (aref row j))))))

(defun copy-grid (grid)
  (let* ((height (grid-height grid))
	 (new (make-vector height nil)))
    (dotimes (i height)
      (aset new i (copy-sequence (aref grid i))))
    new))

(defun reset-grid (a b)
  (dotimes (i (grid-height a))
    (aset b i (copy-sequence (aref a i)))))

(defun antennas (grid)
  (let ((antennas (make-hash-table)))
    (dotimes (i (grid-height grid))
      (dotimes (j (grid-width grid))
	(let* ((pos (cons i j))
	       (c (gref grid pos)))
	  (unless (eq c ?.)
	    (let ((l (gethash c antennas)))
	      (push pos l)
	      (puthash c l antennas))))))
    antennas))

(defun combine (list)
  (let ((pairs nil))
    (when (cdr list)
      (let ((a (car list)))
	(dolist (b (cdr list))
	  (push (cons a b) pairs)))
      (when (cddr list)
	(setq pairs (append pairs (combine (cdr list))))))
    pairs))

(defun antenna-pairs (antennas)
  (let ((pairs nil))
    (maphash (lambda (_ l)
	       (setq pairs (append pairs (combine l))))
	     antennas)
    pairs))

(defun antipoints (n m)
  (let ((d (- n m)))
    (cons (+ n d) (- m d))))

(defun mark-antinodes (grid p)
  (let* ((a (car p))
	 (b (cdr p))
	 (c (antipoints (car a) (car b)))
	 (d (antipoints (cdr a) (cdr b))))
    (gset grid (cons (car c) (car d)) ?#)
    (gset grid (cons (cdr c) (cdr d)) ?#)))

(defun count-antinodes (grid)
  (let ((count 0))
    (dotimes (i (grid-height grid))
      (dotimes (j (grid-width grid))
	(when (eq (gref grid (cons i j)) ?#)
	  (incf count))))
    count))

(defun puzzle-8a ()
  (let* ((grid (read-grid "data/input-8.txt"))
	 (mark (make-grid (grid-height grid) (grid-width grid)))
	 (antennas (antennas grid)))
    (dolist (p (antenna-pairs antennas))
      (mark-antinodes mark p))
    (count-antinodes mark)))

(defun antipoints-2 (n m factor)
  (let ((d (- n m)))
    (cons (+ n (* d factor)) (- m (* d factor)))))

(defun mark-antinodes-2 (grid p)
  (let ((a (car p))
	(b (cdr p)))
    ;; rather than thinking too much about bounds, just keep
    ;; increasing the number of factors until the result converges
    (dotimes (f 60)
      (let ((c (antipoints-2 (car a) (car b) f))
	    (d (antipoints-2 (cdr a) (cdr b) f)))
	(gset grid (cons (car c) (car d)) ?#)
	(gset grid (cons (cdr c) (cdr d)) ?#)))))

(defun puzzle-8b ()
  (let* ((grid (read-grid "data/input-8.txt"))
	 (mark (make-grid (grid-height grid) (grid-width grid)))
	 (antennas (antennas grid)))
    (dolist (p (antenna-pairs antennas))
      (mark-antinodes-2 mark p))
    (count-antinodes mark)))
