;; -*- lexical-binding: t -*-

(defvar p-rx "p=\\([0-9]\\{1,3\\}\\),\\([0-9]\\{1,3\\}\\)")
(defvar v-rx "v=\\(-?[0-9]\\{1,3\\}\\),\\(-?[0-9]\\{1,3\\}\\)")

(defun match-pair ()
  (cons (read (match-string 1))
	(read (match-string 2))))

(defun read-robots (file)
  (with-temp-buffer
    (insert-file-contents file)
    (let ((robots nil))
      (while (re-search-forward p-rx nil t)
	(let ((p (match-pair)))
	  (re-search-forward v-rx)
	  (push (cons p (match-pair)) robots)))
      (nreverse robots))))

(defun simulate1 (r bounds)
  (pcase-let ((`(,bx . ,by) bounds)
	      (`((,rx . ,ry) ,rvx . ,rvy) r))
    (let ((rp (car r)))
      (setcar rp (mod (+ rx rvx) bx))
      (setcdr rp (mod (+ ry rvy) by)))))

(defun simulate (robots bounds secs)
  (dotimes (_ secs)
    (dolist (r robots)
      (simulate1 r bounds))))

(defun quarter (bounds)
  (let* ((x (car bounds))
	 (y (cdr bounds))
	 (x‾ (/ (1- x) 2))
	 (y‾ (/ (1- y) 2)))
    (list (cons (cons 0 x‾)
		(cons 0 y‾))
	  (cons (cons (1+ x‾) x)
		(cons 0 y‾))
	  (cons (cons 0 x‾)
		(cons (1+ y‾) y))
	  (cons (cons (1+ x‾) x)
		(cons (1+ y‾) y)))))

(defun inside (r q)
  (pcase-let ((`((,rx . ,ry)) r)
	      (`((,qx1 . ,qx2) ,qy1 . ,qy2) q))
    (and (>= rx qx1) (< rx qx2)
	 (>= ry qy1) (< ry qy2))))

(defun safety-factor (robots bounds)
  (let ((factor 1))
    (dolist (q (quarter bounds))
      (let ((n 0))
	(dolist (r robots)
	  (when (inside r q)
	    (incf n)))
	(setq factor (* factor n))))
    factor))

(defun puzzle-14a ()
  ;; example-14.txt (bounds '(11 . 7)): 12
  ;; input-14.txt (bounds '(101 . 103)): 233709840
  (let ((robots (read-robots "data/input-14.txt"))
	(bounds '(101 . 103)))
    (simulate robots bounds 100)
    (safety-factor robots bounds)))

(defun insert-grid (g)
  (seq-do (lambda (r) (seq-do #'insert r) (insert ?\n)) g))

(defun grid-height (grid)
  (length grid))

(defun grid-width (grid)
  (length (aref grid 0)))

(defun gset (grid pos value)
  (pcase-let ((`(,i . ,j) pos))
    (when (and (>= i 0) (< i (length grid)))
      (let ((row (aref grid i)))
	(when (and (>= j 0) (< j (length row)))
	  (aset row j value))))))

(defun gref (grid pos)
  (pcase-let ((`(,i . ,j) pos))
    (when (and (>= i 0) (< i (length grid)))
      (let ((row (aref grid i)))
	(when (and (>= j 0) (< j (length row)))
	  (aref row j))))))

(defun make-grid (height width)
  (let ((grid (make-vector height nil)))
    (dotimes (i height)
      (aset grid i (make-vector width ?.)))
    grid))

(defun wipe-grid (grid)
  (dotimes (i (grid-height grid))
    (dotimes (j (grid-width grid))
      (gset grid (cons i j) ?.))))

(defun robot-grid (grid robots)
  (dolist (r robots)
    (gset grid (cons (cdar r) (caar r)) ?X)))

(defun suspicious-p (grid n)
  (catch :suspicious
    (dotimes (i (grid-height grid))
      (let ((last nil))
	(dotimes (j (grid-width grid))
	  (cond ((eq (gref grid (cons i j)) ?.)
		 (setq last nil))
		((null last)
		 (setq last j))
		((> (- j last) n)
		 (throw :suspicious t))))))))

(defun watch-robots (grid robots bounds times)
  (let* ((again t)
	 (n 0)
	 (p (make-progress-reporter "Simulating" n times)))
    (while (and again (< n times))
      (wipe-grid grid)
      (robot-grid grid robots)
      (simulate robots bounds 1)
      (if (suspicious-p grid 20)
	  (setq again nil)
	(incf n)
	(progress-reporter-update p n)))
    (progress-reporter-done p)
    (and (< n times) (cons n grid))))

(defun puzzle-14b ()
  ;; input-14.txt: 6620
  (let* ((robots (read-robots "data/input-14.txt"))
	 (bounds '(101 . 103))
	 (grid (make-grid (cdr bounds) (car bounds))))
    (when-let* ((found (watch-robots grid robots bounds 10000)))
      (insert-grid (cdr found))
      (car found))))
