;; -*- lexical-binding: t -*-

(defun read-grid (file)
  (with-temp-buffer
    (insert-file-contents file)
    (let* ((height (line-number-at-pos (1- (point-max))))
	   (grid (make-vector height nil)))
      (dotimes (i height)
	(let ((row (buffer-substring (point) (line-end-position))))
	  (aset grid i row)
	  (forward-line)))
      grid)))

(defun grid-height (grid)
  (length grid))

(defun grid-width (grid)
  (length (aref grid 0)))

(defun gset (grid pos value)
  (pcase-let ((`(,i . ,j) pos))
    (when (and (>= i 0) (< i (length grid)))
      (let ((row (aref grid i)))
	(when (and (>= j 0) (< j (length row)))
	  (aset row j value))))))

(defun gref (grid pos)
  (pcase-let ((`(,i . ,j) pos))
    (when (and (>= i 0) (< i (length grid)))
      (let ((row (aref grid i)))
	(when (and (>= j 0) (< j (length row)))
	  (aref row j))))))

(defun make-grid (height width)
  (let ((grid (make-vector height nil)))
    (dotimes (i height)
      (aset grid i (make-vector width ?.)))
    grid))

(defun grid-like (grid)
  (make-grid (grid-height grid) (grid-width grid)))

(defun copy-grid (grid)
  (let* ((height (grid-height grid))
	 (new (make-vector height nil)))
    (dotimes (i height)
      (aset new i (copy-sequence (aref grid i))))
    new))

(defun count-grid (grid c)
  (let ((count 0))
    (dotimes (i (grid-height grid))
      (dotimes (j (grid-width grid))
	(when (eq (gref grid (cons i j)) c)
	  (incf count))))
    count))

(defun numchar (n)
  (+ n 48))

(defun trailheads (grid)
  (let ((heads nil))
    (dotimes (i (grid-height grid))
      (dotimes (j (grid-width grid))
	(let ((pos (cons i j)))
	  (when (eq (gref grid pos) (numchar 0))
	    (push pos heads)))))
    heads))

(defun step (grid mark pos c)
  (when (eq (gref grid pos) (+ c 1))
    (walk-trail grid mark pos)))

(defun walk-trail (grid mark pos)
  (when-let* ((c (gref grid pos)))
    (if (eq c (numchar 9))
	(gset mark pos ?X)
      (pcase-let ((`(,i . ,j) pos))
	(step grid mark (cons (1+ i) j) c)
	(step grid mark (cons i (1+ j)) c)
	(step grid mark (cons (1- i) j) c)
	(step grid mark (cons i (1- j)) c)))))

(defun puzzle-10a ()
  (let* ((grid (read-grid "data/input-10.txt"))
	 (heads (trailheads grid))
	 (sum 0))
    (dolist (pos heads)
      (let ((mark (grid-like grid)))
	(walk-trail grid mark pos)
	(incf sum (count-grid mark ?X))))
    sum))

(defun step-2 (grid pos c)
  (if (eq (gref grid pos) (+ c 1))
      (rating grid pos)
    0))

(defun rating (grid pos)
  (let ((c (gref grid pos)))
    (cond ((null c) 0)
	  ((eq c (numchar 9)) 1)
	  (t (pcase-let ((`(,i . ,j) pos))
	       (+ (step-2 grid (cons (1+ i) j) c)
		  (step-2 grid (cons i (1+ j)) c)
		  (step-2 grid (cons (1- i) j) c)
		  (step-2 grid (cons i (1- j)) c)))))))

(defun puzzle-10b ()
  (let* ((grid (read-grid "data/input-10.txt"))
	 (heads (trailheads grid))
	 (sum 0))
    (dolist (pos heads)
      (let ((n (rating grid pos)))
	(incf sum n)))
    sum))
