;; -*- lexical-binding: t -*-

(defun read-grid (file)
  (with-temp-buffer
    (insert-file-contents file)
    (let* ((height (line-number-at-pos (1- (point-max))))
	   (grid (make-vector height nil)))
      (dotimes (i height)
	(let ((row (buffer-substring (point) (line-end-position))))
	  (aset grid i row)
	  (forward-line)))
      grid)))

(defun insert-grid (grid)
  (seq-do (lambda (row)
	    (insert row)
	    (insert ?\n))
	  grid))

(defun grid-height (grid)
  (length grid))

(defun grid-width (grid)
  (length (aref grid 0)))

(defun gset (grid pos value)
  (pcase-let ((`(,i . ,j) pos))
    (when (and (>= i 0) (< i (length grid)))
      (let ((row (aref grid i)))
	(when (and (>= j 0) (< j (length row)))
	  (aset row j value))))))

(defun gref (grid pos)
  (pcase-let ((`(,i . ,j) pos))
    (when (and (>= i 0) (< i (length grid)))
      (let ((row (aref grid i)))
	(when (and (>= j 0) (< j (length row)))
	  (aref row j))))))

(defun make-grid (height width)
  (let ((grid (make-vector height nil)))
    (dotimes (i height)
      (aset grid i (make-vector width nil)))
    grid))

(defun grid-like (grid)
  (make-grid (grid-height grid) (grid-width grid)))

(defun copy-grid (grid)
  (let* ((height (grid-height grid))
	 (new (make-vector height nil)))
    (dotimes (i height)
      (aset new i (copy-sequence (aref grid i))))
    new))

(defun count-grid (grid c)
  (let ((count 0))
    (dotimes (i (grid-height grid))
      (dotimes (j (grid-width grid))
	(when (eq (gref grid (cons i j)) c)
	  (incf count))))
    count))

(defun around (grid pos)
  (pcase-let ((`(,i . ,j) pos))
    (list (gref grid (cons (1- i) j))
	  (gref grid (cons i (1+ j)))
	  (gref grid (cons (1+ i) j))
	  (gref grid (cons i (1- j))))))

(defun perimeter (grid plots c)
  (let ((count 0))
    (dolist (pos plots)
      (dolist (d (around grid pos))
	(unless (eq d c)
	  (incf count))))
    count))

(defun adjacentp (a b)
  (pcase-let ((`(,ai . ,aj) a)
	      (`(,bi . ,bj) b))
    (or (and (eq ai bi)
	     (or (eq aj (1- bj))
		 (eq aj (1+ bj))))
	(and (eq aj bj)
	     (or (eq ai (1- bi))
		 (eq ai (1+ bi)))))))

(defun stick (region regions)
  (seq-find (lambda (plots)
	      (seq-find (lambda (other)
			  (seq-find (lambda (plot)
				      (adjacentp plot other))
				    region))
			plots))
	    regions))

(defun consolidate (plots)
  (let ((regions (mapcar #'list plots))
	(changed t))
    (while changed
      (setq changed nil)
      (dolist (region regions)
	(let ((other (remq region regions)))
	  (when-let* ((stuck (stick region other)))
	    (nconc stuck region)
	    (setq regions other)
	    (setq changed t)))))
    regions))

(defun region-price (grid plots c)
  (let ((area (length plots))
	(perimeter (perimeter grid plots c)))
    (* area perimeter)))

(defun puzzle-12a ()
  (let ((grid (read-grid "data/input-12.txt"))
	(plots (make-hash-table))
	(total 0))
    (dotimes (i (grid-height grid))
      (dotimes (j (grid-width grid))
	(let* ((pos (cons i j))
	       (c (gref grid pos)))
	  (push pos (gethash c plots)))))
    (maphash (lambda (c plots)
	       (dolist (region (consolidate plots))
		 (incf total (region-price grid region c))))
	     plots)
    total))

(defun deltas (dir)
  (pcase dir
    (:up    '(-1 .  0))
    (:right '( 0 .  1))
    (:down  '( 1 .  0))
    (:left  '( 0 . -1))))

(defun scanwise (dir)
  (pcase dir
    (:up :right)
    (:right :down)
    (:down :right)
    (:left :down)))

(defun pos-add (a b)
  (cons (+ (car a) (car b))
	(+ (cdr a) (cdr b))))

(defun look (grid pos dir)
  (let ((d (deltas dir)))
    (gref grid (pos-add pos d))))

(defun borders (pos)
  (pcase-let ((`(,i . ,j) pos))
    (list (list :up (1- i) j)
	  (list :right i (1+ j))
	  (list :down (1+ i) j)
	  (list :left i (1- j)))))

(defun mark-side (grid mark pos dir c)
  ;; after counting one boundary between regions, mark all of the
  ;; plots along its edge as accounted for
  (let ((next (deltas (scanwise dir))))
    ;; move within the current region along the current edge...
    (while (and (eq c (gref grid pos))
		;; ... as long as the border holds
		(not (eq c (look grid pos dir))))
      (let ((dirs (gref mark pos)))
	(gset mark pos (cons dir dirs)))
      (setq pos (pos-add pos next)))))

(defun sides (grid mark plots c)
  (let ((count 0))
    (dolist (pos plots)
      (dolist (border (borders pos))
	(pcase-let ((`(,dir ,i ,j) border))
	  (let ((d (gref grid (cons i j))))
	    (unless (or (eq d c) (memq dir (gref mark pos)))
	      (mark-side grid mark pos dir c)
	      (incf count))))))
    count))

(defun discounted-price (grid mark plots c)
  (let ((area (length plots))
	(sides (sides grid mark plots c)))
    (* area sides)))

(defun puzzle-12b ()
  (let* ((grid (read-grid "data/input-12.txt"))
	 (mark (grid-like grid))
	 (plots (make-hash-table))
	 (total 0))
    (dotimes (i (grid-height grid))
      (dotimes (j (grid-width grid))
	(let* ((pos (cons i j))
	       (c (gref grid pos)))
	  (push pos (gethash c plots)))))
    (let* ((n 0)
	   (max (hash-table-count plots))
	   (p (make-progress-reporter "Computing" n max)))
      (maphash (lambda (c plots)
		 (dolist (region (consolidate plots))
		   (let ((price (discounted-price grid mark region c)))
		     (incf total price)))
		 (incf n)
		 (progress-reporter-update p n))
	       plots)
      (progress-reporter-done p))
    total))
